athenareader:
  output:
    # options are default, markdown, csv, html
    render: markdown
    pagesize: 2
    # options are default, StyleBold, StyleColoredBright, StyleColoredDark, StyleColoredBlackOnBlueWhite, StyleColoredBlackOnCyanWhite, StyleColoredBlackOnGreenWhite
    style: StyleColoredBright
    rowonly: false
    moneywise: true

  input:
    bucket: "s3://henrywutest/"
    region: "us-east-1"
    database: sampledb
    admin: false
